/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.006072,\"B\": 1.1095029e-05,\"Lq\": 0.000474,\"poleCount"
  "\": 4,\"rated_current\": 2.2,\"J\": 3.859584e-06,\"velocity\": {\"nominal\": 418"
  ".8790205,\"maximum\": 837.758040957,\"units\": \"rad\\/s\"},\"L\": 0.0003905,\"R"
  "\": 0.56924,\"current\": {\"maximum\": {\"continuous\": 2.2,\"peak\": 2.2},\"uni"
  "ts\": \"A\"},\"Ld\": 0.000307,\"Ke\": 0.0283624644552,\"id\": \"linix-45ZWN24-40"
  "\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": "
  "{\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"propert"
  "ies\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_d"
  "eceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"error"
  "Limit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\""
  "duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detec"
  "t\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture"
  "\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": "
  "\"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": "
  "\"qei\"},{\"name\": \"SCCP1\",\"type\": \"timer\"},{\"name\": \"TMR1\",\"type\":"
  " \"timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"CMP1\",\"type"
  "\": \"cmp\"}]},\"version\": \"5.8.4\",\"peripheral_library\": {\"name\": \"melod"
  "y\",\"version\": \"NA\"}},\"data_model\": {\"schema_version\": 5},\"motorBench\""
  ": {\"commit_id\": \"c114bdc6e8ebb44adc1b5cd1e6b92ea0b107647e\",\"version\": \"2."
  "55.0\"},\"MCAF\": {\"build\": {\"commit_id\": \"132024\",\"date_str\": \"2026 Fe"
  "b 13\",\"hostname\": \"motor-control-mcaf-tags-builder-r9-2frc31-1-4qzv8-0zfbw-3"
  "kggr\",\"time\": 1771007857.63,\"time_iso\": \"2026-02-13T18:37:37.630250\",\"ti"
  "me_str\": \"2026 Feb 13 18:37\",\"type\": \"release\",\"username\": \"jenkins\","
  "\"version\": \"R9\\/RC31\"},\"build_time\": 1771007857.63,\"build_time_iso\": \""
  "2026-02-13T18:37:37.630250\",\"build_time_str\": \"2026 Feb 13 18:37\",\"commit_"
  "id\": \"132024\",\"version\": \"R9\\/RC31\"}},\"scdata\": {\"setup\": {\"communi"
  "cations\": {\"baudrate\": 625000},\"analysis\": {\"spindown_time\": {\"units\": "
  "\"s\",\"value\": 1.0},\"max_motor_speed\": {\"units\": \"rad\\/s mechanical\",\""
  "value\": 2094.4}},\"calibration\": {\"vdc\": {\"units\": \"V\",\"value\": 24.0},"
  "\"resistor\": {\"units\": \"ohms\",\"value\": 12.0}}}},\"autotune_result\": {\"c"
  "urrent\": {\"Kp\": 0.613899846464,\"phase_margin\": 80.0,\"wc\": 2065.76539605,"
  "\"Ki\": 1268.17305946,\"pi_phase_lag\": 45.0},\"velocity\": {\"Kp\": 0.009803028"
  "79443,\"phase_margin\": 65.0,\"wc\": 87.0073087293,\"Ki\": 0.150395480233,\"pi_p"
  "hase_lag\": 10.0}},\"code_generation_tag_map\": {\"application\": \"sample\",\"d"
  "iagnostics\": \"x2cscope\"},\"operating_range\": {\"velocity\": {\"units_qualifi"
  "er\": \"mechanical\",\"units\": \"rad\\/s\",\"minimum\": 261.7995}},\"build\": {"
  "\"hardware_spec\": \"mclv2:33ck256mp508_extopamp_pim\",\"normfactor_associations"
  "\": [{\"context\": null,\"annotations\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\""
  ",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MO"
  "TOR_DATA.omegaCtrl.outMin\",\"MCAF_MOTOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.omegaCtrl.integrator\"],\"unit\""
  ": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHA"
  "BETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin"
  "\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\"MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MO"
  "TOR_DATA.iqCtrl.outMax\"],\"unit\": \"V\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTO"
  "R_DATA.idCtrl.integrator\",\"MCAF_MOTOR_DATA.iqCtrl.integrator\"],\"unit\": \"V"
  "\",\"q\": 31},{\"typerefs\": [\"MCAF_U_DUTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{"
  "\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\"unit\": \"theta_e\",\"q\": 15},{\"typere"
  "fs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": \"theta_m\",\"q\": 15},{\"typerefs\": ["
  "\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"omega_m\",\"q\": 15},{\"typerefs\": [\"MCA"
  "F_U_VELOCITY_ELEC\"],\"unit\": \"omega_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_V"
  "ELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dtheta_elec_dt\",\"q\": 15},{\"typerefs\":"
  " [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Temperature\",\"q\": 15},{\"typerefs\": ["
  "\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSIONLESS_SINCOS\"],\"unit\": 1,\"q\": 15}"
  ",{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN\"],\"unit\": 1,\"q\": 14},{\"typerefs"
  "\": [\"MCAF_U_NORMALIZED_Q15\"],\"unit\": 1,\"q\": 15}]}]},\"drive\": {\"iout\":"
  " {\"measurement\": {\"compensation\": {\"channels\": [\"a\",\"b\"],\"values\": {"
  "\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"offset\": {\"samples\": 128,\"filterGain\":"
  " 0.25},\"gain\": {\"samples\": 128}}},\"time_constant\": 5.97e-07,\"fullscale\":"
  " 22.04,\"maximum\": {\"continuous\": 16.0,\"peak\": 16.0},\"units\": \"A\"},\"es"
  "timator\": {\"type\": \"pll\",\"runtimeSelect\": false,\"smo\": {\"ke_low_limit"
  "\": 0.01},\"omega1\": 732.0,\"tau\": 0.00219},\"flux_control\": {\"emag_tau\": 0"
  ".001638,\"idref_tau\": 0.006552},\"temperature\": {\"fullscale\": 327.68,\"units"
  "\": \"C\"},\"pwm\": {\"adc_sampling_delay\": 0,\"period\": 5e-05,\"duty_cycle\":"
  " {\"maximum\": 0.945,\"minimum\": 0.014},\"deadtime\": 5.9e-07},\"mcaf\": {\"adc"
  "\": {\"triggerSettings\": {\"noTrigger\": \"NO_TRIGGER\",\"trigger1\": \"PWM1_TR"
  "IGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"channels\": {\"prefix\": \"MCAF_ADC_"
  "\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCL"
  "INK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required\": {\"single_channel\": [\"DCLINK_C"
  "URRENT\",\"DCLINK_VOLTAGE\"],\"dual_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURR"
  "ENT\",\"DCLINK_VOLTAGE\"],\"triple_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRE"
  "NT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\"]},\"optional\": [\"POTENTIOMETER\",\""
  "PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\""
  "ABSREF_VOLTAGE\"],\"fullList\": [{\"name\": \"PHASEA_CURRENT\",\"c_fragment\": "
  "\"PhaseACurrent\",\"description\": \"phase A current\",\"type\": \"current\"},{"
  "\"name\": \"PHASEB_CURRENT\",\"c_fragment\": \"PhaseBCurrent\",\"description\": "
  "\"phase B current\",\"type\": \"current\"},{\"name\": \"PHASEC_CURRENT\",\"c_fra"
  "gment\": \"PhaseCCurrent\",\"description\": \"phase C current\",\"type\": \"curr"
  "ent\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fragment\": \"PhaseAVoltage\",\"descrip"
  "tion\": \"phase A voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEB_VOLTAGE\""
  ",\"c_fragment\": \"PhaseBVoltage\",\"description\": \"phase B voltage\",\"type\""
  ": \"voltage\"},{\"name\": \"PHASEC_VOLTAGE\",\"c_fragment\": \"PhaseCVoltage\","
  "\"description\": \"phase C voltage\",\"type\": \"voltage\"},{\"name\": \"DCLINK_"
  "CURRENT\",\"c_fragment\": \"DCLinkCurrent\",\"description\": \"DC link current\""
  ",\"type\": \"current\"},{\"name\": \"DCLINK_VOLTAGE\",\"c_fragment\": \"DCLinkVo"
  "ltage\",\"description\": \"DC link voltage\",\"type\": \"voltage\"},{\"name\": "
  "\"POTENTIOMETER\",\"c_fragment\": \"Potentiometer\",\"description\": \"potentiom"
  "eter voltage\",\"type\": \"voltage\"},{\"name\": \"BRIDGE_TEMPERATURE\",\"c_frag"
  "ment\": \"BridgeTemperature\",\"description\": \"bridge temperature voltage\",\""
  "type\": \"voltage\"},{\"name\": \"ABSREF_VOLTAGE\",\"c_fragment\": \"AbsoluteRef"
  "erenceVoltage\",\"description\": \"absolute reference voltage\",\"type\": \"volt"
  "age\"}]}}},\"metadata\": {\"name\": \"MCLV-48V-300W\",\"id\": \"mclv-48v-300w\"}"
  ",\"vdc\": {\"time_constant\": 2.87e-05,\"nominal\": 24.0,\"fullscale\": 75.9,\"m"
  "aximum\": 26.0,\"units\": \"V\",\"minimum\": 16.0},\"configuration\": {\"charact"
  "eristics\": {\"current\": {\"dcLink\": {\"fullscale\": 22.04,\"timeConstant\": 5"
  ".97e-07},\"phase\": {\"fullscale\": 22.04,\"maximum\": {\"continuous\": 16.0},\""
  "timeConstant\": 5.97e-07}},\"device\": \"dsPIC33CK256MP508\",\"powerOn\": {\"del"
  "ay\": {\"maximum\": 0.05}},\"pwm\": {\"deadTime\": {\"default\": 5.9e-07,\"maxim"
  "um\": 6e-06,\"minimum\": 3.85e-07},\"dutyCycle\": {\"maximum\": 0.945,\"minimum"
  "\": 0.014},\"frequency\": {\"default\": 20000,\"maximum\": 50000,\"minimum\": 10"
  "000}},\"voltage\": {\"dcLink\": {\"default\": 24.0,\"fullscale\": 75.9,\"maximum"
  "\": 26.0,\"minimum\": 16.0,\"timeConstant\": 2.87e-05},\"phase\": {\"fullscale\""
  ": 75.9,\"timeConstant\": 2.87e-05}}},\"identification\": {\"description\": \"MCL"
  "V-48V-300W Inverter Board\",\"displayName\": \"MCLV-48V-300W\",\"id\": \"mclv-48"
  "v-300w\",\"pim_id\": \"33ck256mp508_dim\"},\"peripherals\": {\"adc\": {\"current"
  "\": {\"a\": {\"channel\": \"AN1\",\"inverted\": true,\"signed\": true},\"b\": {"
  "\"channel\": \"AN4\",\"inverted\": true,\"signed\": true},\"c\": {\"channel\": "
  "\"AN16\",\"inverted\": true,\"signed\": true},\"dcLink\": {\"channel\": \"AN0\","
  "\"inverted\": false,\"signed\": true}},\"other\": {\"bridgeTemperature\": {\"cha"
  "nnel\": \"AN18\",\"gain\": 0.50354,\"offset\": 0.5,\"signed\": false},\"potentio"
  "meter\": {\"channel\": \"AN17\",\"signed\": true}},\"samplingTime\": {\"default"
  "\": 3e-07,\"maximum\": 1e-06,\"minimum\": 3e-07},\"voltage\": {\"a\": {\"channel"
  "\": \"AN10\",\"signed\": false},\"absoluteReference\": {\"channel\": \"AN6\",\"n"
  "ominal\": 2.5,\"signed\": false},\"b\": {\"channel\": \"AN11\",\"signed\": false"
  "},\"c\": {\"channel\": \"AN12\",\"signed\": false},\"dcLink\": {\"channel\": \"A"
  "N15\",\"signed\": true}}},\"comparator\": {\"inverted\": false,\"source\": \"CMP"
  "1A\",\"threshold\": 0.95},\"debugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BUTTO"
  "N1\": {\"direction\": \"input\",\"pin\": \"RE10\",\"polarity\": \"active-high\"}"
  ",\"MCAF_BUTTON2\": {\"direction\": \"input\",\"pin\": \"RE11\",\"polarity\": \"a"
  "ctive-high\"},\"MCAF_LED1\": {\"direction\": \"output\",\"pin\": \"RE12\",\"pola"
  "rity\": \"active-high\"},\"MCAF_LED2\": {\"direction\": \"output\",\"pin\": \"RE"
  "13\",\"polarity\": \"active-high\"},\"MCAF_TESTPOINT1\": {\"direction\": \"outpu"
  "t\",\"pin\": \"RE8\",\"polarity\": \"active-high\"}},\"opamp\": {\"enabled\": [1"
  ",2,3]},\"oscillator\": {\"clockSource\": \"external clock\",\"inputClockFrequenc"
  "y\": 8000000},\"pwm\": {\"fault\": {\"polarity\": \"active-high\",\"source\": \""
  "CMP1\"},\"generators\": {\"a\": 1,\"b\": 2,\"c\": 3},\"polarity\": {\"lower\": "
  "\"active-high\",\"upper\": \"active-high\"}},\"qei\": {\"pins\": {\"A\": \"RC4\""
  ",\"B\": \"RC5\",\"Z\": \"RD2\"}},\"uart\": {\"pins\": {\"RX\": \"RD13\",\"TX\": "
  "\"RD14\"}}}},\"idc\": {\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05,"
  "\"velocity\": 0.001},\"processor\": {\"clock_frequency\": 100000000.0,\"device\""
  ": \"dsPIC33CK256MP508\"}},\"config\": {\"ui\": {\"content\": {\"current_measure-"
  "method\": \"dual_channel\",\"current_measure-single_channel-minimumTime\": 2.0,"
  "\"current_measure-single_channel-sampleDelay\": 0.0,\"current_measure-opamp-full"
  "_input_range\": true,\"current_measure-offset_cal-range\": 0.04,\"estimator-type"
  "\": \"pll\",\"estimator-active-pll\": false,\"estimator-active-smo\": false,\"es"
  "timator-active-qei\": false,\"estimator-active-atpll\": false,\"estimator-active"
  "-zsmt\": false,\"estimator-active-ideal\": false,\"operation-min_velocity_ratio"
  "\": 0.25,\"operation-startup_velocity_ratio\": 0.2744,\"operation-max_velocity_r"
  "atio\": 1.25,\"operation-fullscale_base_ratio\": 1.5,\"operation-outer_loop_type"
  "\": \"velocity\",\"operation-saliency-threshold\": 1.25,\"operation-slewrate-acc"
  "el\": 0.5,\"operation-slewrate-decel\": 1.0,\"operation-dyn_current_type\": \"no"
  "ne\",\"operation-stopping-type\": \"minimal_impact\",\"operation-stopping-closed"
  "_loop_parameters-speed\": 0.05,\"operation-stopping-closed_loop_parameters-time"
  "\": 0.5,\"operation-stopping-coastdown-end_velocity\": 0.05,\"operation-stopping"
  "-coastdown-time\": 1.2,\"fault_inject-get_tf-div0\": false,\"fault_inject-get_tf"
  "-missing_data\": false,\"fault_inject-get_tf-raise_value_error\": false,\"fault_"
  "inject-get_tf-raise_custom_error\": false,\"fault_inject-tf-tf_null\": false,\"f"
  "ault_inject-tf-tf_jy\": false,\"fault_inject-tf-tf_jyex\": false,\"fault_inject-"
  "tf-div0\": false,\"fault_inject-tf-tau\": 0.0,\"flux_control-method\": \"none\","
  "\"flux_control-eqn_based-ilimit-region_type\": \"quadratic\",\"flux_control-eqn_"
  "based-ilimit-id_limit\": 0.7,\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\""
  "flux_control-eqn_based-fluxweak_enable\": false,\"flux_control-eqn_based-fw-vdq_"
  "limit\": 0.95,\"flux_control-eqn_based-mtpa_enable\": false,\"deadtimecomp-metho"
  "d\": \"none\",\"deadtimecomp-perphase-current_sign_band\": 0.02,\"deadtimecomp-p"
  "erphase-forward_gain\": 0.0,\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault"
  "_detect-margin_uv\": 2.0,\"fault_detect-margin_ov\": 2.0,\"fault_detect-stall_de"
  "tect_enable\": true,\"startup-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"star"
  "tup-t_align\": 0.0,\"startup-min_total_accel_time\": 250.0,\"startup-torque_scal"
  "e_accel\": 0.15,\"startup-torque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0"
  ",\"startup-omega0\": 0.2,\"startup-theta_converge_rate\": 1.0,\"startup-method\""
  ": \"classic\",\"startup-damping-Imax\": 0.133,\"startup-damping-gainmax\": 40.0,"
  "\"startup-damping-omega_min\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodula"
  "tion-vq_limit\": 1.15,\"overmodulation-include_duty_clipping\": true,\"atpll-tau"
  "1\": 0.1,\"atpll-tau2\": 2.19,\"atpll-kp\": 1.9,\"atpll-ki\": 30.0,\"pll-tau\": "
  "2.19,\"pll-omega1\": 116.5,\"pll-velocity_filter_threshold\": 1.0,\"smo-velocity"
  "_loop_cutoff\": 0.3,\"encoder-lines\": 250.0,\"encoder-index_present\": false,\""
  "encoder-tracking_loop-tau\": 1.5,\"encoder-qei_sync-method\": \"align\",\"encode"
  "r-qei_sync-align-t_align\": 0.5,\"encoder-qei_sync-align-angle_shift\": 30.0,\"e"
  "ncoder-qei_sync-align-angle_init\": -30.0,\"encoder-qei_sync-align_sweep-sweep_r"
  "ate_pow\": 1.0,\"encoder-qei_sync-align_sweep-setup_angle\": 45.0,\"encoder-qei_"
  "sync-pullout-pullout_slip\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-excitatio"
  "n-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau_lpf\": "
  "0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsmt-startup-align_delay\": 1.0,\"zsmt"
  "-startup-pll_lock_time\": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt-startup"
  "-current_limit\": 0.3,\"zsmt-startup-probe_current\": 0.3,\"zsmt-startup-probe_d"
  "uration\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blank"
  "ing_time\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit"
  "-vd\": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-an"
  "gle\": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_th"
  "reshold-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-transition\": 0.2,\"zsmt"
  "-minotaur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correction-current_gain\""
  ": 0.0,\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\""
  "dyn_current1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau"
  "_lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mca"
  "pi-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\""
  ": false,\"board_service-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceT"
  "ime\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"test_harness-perturbat"
  "ion_asymmetric\": false,\"test_harness-codegen-test_harness\": false,\"test_harn"
  "ess-codegen-test_profiling\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge"
  "_params-threshold\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_br"
  "idge_params-slewrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-"
  "vphaseb\": false,\"adc-vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\""
  "version\": {\"schema\": 6.0,\"motorBench\": \"2.55.0\",\"MCAF\": \"R9\"},\"statu"
  "s\": {\"valid\": true}}}}";